# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: mosdns_config

on:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '18 13 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build

    - name: seting
      run: bash mosdns_config_gen.sh

    - name: get_time
      run: |
        TIME="$(TZ='Asia/Shanghai' date +%Y%m%d')"
        echo "TIME=$TIME" >> $GITHUB_ENV
     
    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.TIME }}
        title: ${{ env.NOW }}
        prerelease: false
        files: |
          mosdns_config/*
          mosdns_config/mosdns_ip/*
          mosdns_config/mosdns_site/*

          
